server:
  servlet:
    context-path: "/api/v1/"
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://your-db-url/your-schema-name""
    username: "your-db-username"
    password: "your-db-password"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
      enabled: true
security:
  jwt:
    secret-key: "your-jwt-secret-key"
    expiration: 432000000 # 5 days
